#!/bin/sh
set -e

echo "==> Building tests"
cmake -S . -B build-vscode > /dev/null
cmake --build build-vscode --target JX11Tests -j8

echo "==> Running tests"
ctest --test-dir build-vscode --output-on-failure
